apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: taskflow-api
          image: hashicorp/http-echo:latest
          args:
            - "-text=Halo dari TaskFlow v1! Fitur Baru New"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
