apiVersion: v1
kind: Service
metadata:
  name: taskflow-api
  namespace: taskflow-dev
spec:
  type: NodePort
  selector:
    app: taskflow-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
